# 工作流名称，不设置的话默认取配置文件名
name: md2pdf
# 指定触发 workflow 的条件
# 指定触发事件时，可以限定分支或标签
# 当前是 只有 branches 分支上触发 push 事件时才执行工作流任务
on:
  push:
    branches:
      - main

# 工作流执行的一个或多个任务
jobs:
  # 任务名称
  test-conversion:
    # 任务运行的容器类型（虚拟机环境）
    runs-on: ubuntu-latest
    name: md2pdf

    steps:
      - uses: actions/checkout@v2
      
      - name: md to PDF
        run: |
          yarn install
          npx md-to-pdf ./md/*.md --md-file-encoding utf-8
          ls
        
      - uses: actions/upload-artifact@v2
        with:
          name: output
          path: ./md/*.pdf
